### ISSUE TITLE
Show alternative market

### ISSUE THREAD

**Issue by xmha97** [yasandev/yasan-launcher-issues#20]
Hi, I disabled Google Play Store and using Aurora Store.
![Screenshot_2022-02-23-03-02-06-843_yasan.space.mnml.ai.launcher.dev.jpg](https://user-images.githubusercontent.com/23485114/155237661-3513284f-8955-4cd9-be7d-900fd0206f86.jpg)
I want to see other stores when I click on the Google Play icon.

**Comment by yasanglass** [comment]
That button should let you select your market app but obviously, it isn't now. Will be fixed. But in general, the launcher does a lot with Play Store and might not even be usable without Play Store later on due to many reasons.
