### ISSUE TITLE
Exiting search still not working fine

### ISSUE THREAD

**Issue by Piripe** [yasandev/yasan-launcher-issues#25]
**Describe the bug**
I still can't close the search easily

**To Reproduce**
1. Open your *beautiful* search
2. Close search

**Expected behavior**
Close the search correctly

**Screenshots**

https://user-images.githubusercontent.com/77517308/156788857-0412ad51-910b-4b74-87bf-a86f6fdca14e.mp4

**Smartphone**
 - Device: OnePlus Nord
 - OS: Android 11 (OxygenOS)
 - Browser: Firefox (Still the best browser)
 - Version: 22.03

**Additional context**
It's funny but I lost a lot a time

**Comment by yasanglass** [comment]
hmm, thats weird. It works perfectly fine for me. I'll look into it.

**Comment by yasanglass** [comment]
@Piripe I am publishing v0.8.6 now and it should be fixed on this version. Please check and reopen the issue if the issue is still not fixed. Thank you for your report again.
