### ISSUE TITLE
Move the back button of the search above the search bar

### ISSUE THREAD

**Issue by Piripe** [yasandev/yasan-launcher-issues#26]
**Is your feature request related to a problem? Please describe.**
It's not a problem, but I don't like when the back button moves by itself

![I'M FRENCH (but anyway)](https://user-images.githubusercontent.com/77517308/156792313-882572fa-825e-413e-bb00-5571ec8ff2f1.jpg)

**Comment by Piripe** [comment]
I've a new concept (Because I don't like the horizontal scroll when we have more than 5 results)
You could do that

![I'M FRENCH (but anyway)](https://user-images.githubusercontent.com/77517308/156811609-d115bb74-944a-4f6d-ac01-ca96b26e6949.jpg)

**Comment by yasanglass** [comment]
Well, there is a reason it was never a grid. But I might be able to add the *option* to choose between the two styles.

Also, the whole search UI & screen are going to be extremely modified soon as the whole search screen does not feel that great IMO. So doing too much work on the current version is unwise.

**Comment by yasanglass** [comment]
The Search screen layout is fully changed on 0.8.6+ and even though it's not final yet, the title bar will never be moved to top again due to consistency. Please open a new issue if you have suggestions to improve the new layout.
