### ISSUE TITLE
Wallpaper keeps changing on me and I think it's this launcher..

### ISSUE THREAD

**Issue by misst70** [yasandev/yasan-launcher-issues#27]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by misst70** [comment]
My wallpaper won't stay the same

**Comment by yasanglass** [comment]
YASAN launcher does not change your wallpaper at any time or situation. I can assure you that its caused by something else.
