### ISSUE TITLE
On the search screen, it should be pressed 2x the onscreen back button

### ISSUE THREAD

**Issue by sandorfimarci** [yasandev/yasan-launcher-issues#31]
**Describe the bug**
When open the search screen by swipe up, you should press 2x the back button under the search field.

**To Reproduce**
1. Go to Homescreen
2. Swipe up to search
3. Press the back button under the search field.

**Expected behavior**
It should be pressed only once not twice.

**Smartphone (please complete the following information):**
 - Device: Huawei p20 lite
 - OS: Android 9
 - Version 0.8.5

**Comment by yasanglass** [comment]
Thanks for reporting this bug. I had noticed it but had never figured out it was related to the swipe action! Ill look into it!

**Comment by yasanglass** [comment]
@sandorfimarci I am publishing v0.8.6 now and it should be fixed on this version. Please check and reopen the issue if the issue is still not fixed. Thank you for your report again.
