### ISSUE TITLE
Change font colors 

### ISSUE THREAD

**Issue by misst70** [yasandev/yasan-launcher-issues#33]

**Comment by yasanglass** [comment]
There was never a font color option. Only the option to choose colors for all the elements on Home. That color picker system is removed temporarily and a better and easier to use system is going to be added soon.

**Comment by misst70** [comment]
That's what I meant I was wondering what happened to it. So there will be
something like that later on added on? Can u please figure out how to add
widgets too? I would really appreciate that thank you.

**Comment by yasanglass** [comment]
Everything takes time so be patient please :)
